package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// demoTapePath is the VHS script that renders image/demo.gif, the first thing a
// reader sees in the README.
const demoTapePath = "../docs/demo.tape"

// TestDemoTapeCommandsStillWork runs every career command the demo tape types
// and requires each to exit 0.
//
// A GIF cannot be regenerated byte-for-byte (VHS output varies with timing,
// fonts and the encoder), so CI cannot diff it to prove the demo is current.
// What can be checked deterministically is the thing that actually rots: the
// command lines inside the tape. Rename a subcommand or drop a flag and this
// test fails here, instead of the next `make demo` quietly recording a terminal
// full of usage errors.
func TestDemoTapeCommandsStillWork(t *testing.T) {
	t.Parallel()

	commands := careerCommandsInTape(t, demoTapePath)
	if len(commands) == 0 {
		t.Fatalf("%s types no career commands; the tape or this parser is wrong", demoTapePath)
	}

	examples, err := filepath.Abs("../examples")
	if err != nil {
		t.Fatal(err)
	}

	for _, command := range commands {
		t.Run(command, func(t *testing.T) {
			t.Parallel()

			// The tape runs from the checkout root, so paths like
			// examples/resume.yaml have to resolve. Copy the fixtures into the
			// scenario's own directory rather than writing PDFs into the repo.
			dir := t.TempDir()
			copyDir(t, examples, filepath.Join(dir, "examples"))

			app, stdout, stderr := newTestApp(dir)
			args := strings.Fields(command)
			if code := app.Run(args[1:]); code != 0 {
				t.Errorf("%q exited with %d\nstdout: %s\nstderr: %s",
					command, code, stdout.String(), stderr.String())
			}
		})
	}
}

// careerCommandsInTape returns the career command lines a VHS tape types. VHS
// keeps the typed text in `Type "..."` directives; everything else in the file
// (Set, Sleep, Hide, shell one-liners) is not a career invocation.
func careerCommandsInTape(t *testing.T, path string) []string {
	t.Helper()

	data, err := os.ReadFile(path) //nolint:gosec // a test-supplied path inside the repository
	if err != nil {
		t.Fatal(err)
	}

	var commands []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, `Type "`) || !strings.HasSuffix(line, `"`) {
			continue
		}
		typed := strings.TrimSuffix(strings.TrimPrefix(line, `Type "`), `"`)
		if !strings.HasPrefix(typed, "career ") {
			continue
		}
		commands = append(commands, typed)
	}
	return commands
}

// copyDir copies a directory one level deep, which is all the fixture tree needs.
func copyDir(t *testing.T, src, dst string) {
	t.Helper()

	if err := os.MkdirAll(dst, 0o750); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(src)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		data, err := os.ReadFile(filepath.Join(src, entry.Name())) //nolint:gosec // fixture files inside the repository
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(dst, entry.Name()), data, 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

// TestDemoTapeRendersTheReadmeGIF pins the output path the tape writes. The
// README embeds image/demo.gif; a tape that renders somewhere else leaves the
// README showing a stale image with nothing failing.
func TestDemoTapeRendersTheReadmeGIF(t *testing.T) {
	t.Parallel()

	data, err := os.ReadFile(demoTapePath)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(data, []byte("Output image/demo.gif")) {
		t.Errorf("%s does not render image/demo.gif, which README.md embeds", demoTapePath)
	}
}
